In [ ]:
# from LevelDetector import LevelDetector
from detect import Locator
import cv2
import numpy as np

tube_position = []
window_position1 = []
window_position2 = []
count = 0
speed = 1

#定位液面
locator = Locator(tube_extract='sift', tube_classify='svm', window_extract='lbp', window_classify='svm')
cap = cv2.VideoCapture('data/tube.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    count += 1
    if count == 1:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
#         tube_position = locator.locate_tube(gray)
#         tube_position.sort(key=lambda x:x[2])
        tube_position = [[0, 271, 33, 76], [0, 271, 81, 115]]
        tube1 = gray[tube_position[0][0]:tube_position[0][1], tube_position[0][2]:tube_position[0][3]]
        tube2 = gray[tube_position[1][0]:tube_position[1][1], tube_position[1][2]:tube_position[1][3]]
#         window_position1 = locator.locate_window(tube1, 5)
#         print(window_position1)
#         window_position1 = list(window_position1)
#         window_position1.sort(key=lambda x:x[0])
#         print(window_position1)
        window_position1 = [[192, 216, 47, 59],
                             [159, 183, 47, 56],
                             [121, 148, 45, 56],
                             [85, 112, 46, 58],
                             [49, 77, 48, 61]]
#         window_position2 = locator.locate_window(tube2, 7)
#         print(window_position2)
#         window_position2 = list(window_position2)
#         window_position2.sort(key=lambda x:x[0])
#         print(window_position2)
        window_position2 = [[219, 244, 95, 107],
                             [185, 210, 92, 104],
                             [150, 177, 90, 102],
                             [113, 141, 89, 101],
                             [76, 105, 89, 101],
                             [40, 68, 90, 103],
                             [5, 33, 92, 105]]
        detector1 = LevelDetector(1, tube_position[0], window_position1)
        detector2 = LevelDetector(2, tube_position[1], window_position2)
        
    
    cur_level, level_scale = detector1.detect_level(frame)
    cv2.line(frame, (45, int(cur_level)), (60, int(cur_level)), (0, 0, 255), 1)
    text = 'level1: ' + str(round(level_scale, 2))
    cv2.putText(frame, text, (5, 13), cv2.FONT_HERSHEY_COMPLEX_SMALL, 0.6, (0, 0, 255), 1)
#     if not count % 50:
#         print(level_scale1)
    
    cur_level, level_scale = detector2.detect_level(frame)
    cv2.line(frame, (90, int(cur_level)), (105, int(cur_level)), (0, 0, 255), 1)
    text = 'level2: ' + str(round(level_scale, 2))
    cv2.putText(frame, text, (5, 28), cv2.FONT_HERSHEY_COMPLEX_SMALL, 0.6, (0, 0, 255), 1)
#     if not count % 50:
#         print(level_scale2)
    
    frame = cv2.resize(frame, None, fx = 2, fy = 2)
    cv2.imshow("result", frame)
    
    #监听按键
    if not count % 5:
        key = cv2.waitKey(speed) & 0xff
        if key == ord('q'):
            break
        elif key == ord('p'):
            cv2.waitKey()
        elif key == ord('c'):
            speed = 40 - speed

cap.release()
cv2.destroyAllWindows()

In [13]:
min
[[ 47  80  10  28]
 [ 82 115   9  25]
 [117 151   6  25]
 [153 186   8  28]
 [188 220  10  28]]
[[  2  34   8  28]
 [ 35  69   4  24]
 [ 72 106   4  23]
 [108 142   4  23]
 [145 178   3  23]
 [178 212   6  27]
 [214 246   8  29]]

<function putText>